### ISSUE TITLE
Passthrough API is just black

### ISSUE THREAD

**Issue by walking-octopus** [GodotVR/godot_openxr#134]
I tried recompiling the latest version with Passthrough permission enabled, but the viewport background is still black. I tried every method of troubleshooting available, but nothing seems to suggest anything's wrong. I hope someone here can help. Hope it's not a stupid question.

**Comment by BastiaanOlij** [comment]
@walking-octopus not a stupid question at all, as it's brand new there are still a few parts settling down.

So far the main issues we're getting as feedback:
- You need to use the latest 3.x release, there are new export options that enable pass through, I think 3.4.1 RC includes it but not 100% sure
- You must enable pass through from the start, it is not a feature that can be toggled on and off (yet)
- You must use the main viewport for rendering XR content

Also if the whole screen stays black, that usually suggest the initialisation on the Godot side isn't being run.

I've also heard some people having issues with a Quest 2 but since I only have a Quest 1 to test, I don't know if there is a real issue here or if they are missing a step. @m4gr3d you have a Quest 2 on which you test right?

For me the demo project in the repository works right off the bat when pass through is enabled on the first person controller.

**Comment by walking-octopus** [comment]
I was also using the demo first-person controller, but the viewport background stayed black. Can you elaborate on export options? I'm using v3.4.stable.official [206ba70f4] and didn't see any options related to Passthrough API in the export dialog.

**Comment by Abadunala** [comment]
@BastiaanOlij I've tried your steps on my Quest2 in 3.4.1 RC2, both in my own project and demo. When turning on passthrough, the background remains black. But I found that I got an error : "Invalid call. Nonexistent function 'start_passthrough' in base 'Node (OpenXRConfig.gdns)'." Does that means I got a bad version of the addon? I didn't build this module by myself, but downloaded it from the release page.
So I don't know whether it's my own problem or the addon's, hope that would help you.

**Comment by BastiaanOlij** [comment]
Very strange, I need to find some time to test it properly, maybe something to mangled when merging stuff though at face value it seems to all be in place: https://github.com/GodotVR/godot_openxr/blob/master/src/gdclasses/OpenXRConfig.cpp#L61

**Comment by Abadunala** [comment]
Switching to 1.1.1 pre-release version fixes everything, now it works totally fine, thank you for your work here.

**Comment by walking-octopus** [comment]
3.4.1 RC2 added the Passthrough API export option and it worked! Thanks for your help!
