### ISSUE TITLE
Banded lights

### ISSUE THREAD

**Issue by balintmaci** [GodotVR/godot_openxr#149]
There is a problem with rendering on the Oculus Quest 2 (standalone mode) using _OpenXR_ GLES2, but not with _Oculus VR Mobile_ GLES2.

The screenshots below of a scene with many spotlights illustrate this quite well.
![image](https://user-images.githubusercontent.com/13272850/147825934-7a2624f4-b55b-431e-aa83-de7070ee20a8.png)

First image is OVRM runtime

![image](https://user-images.githubusercontent.com/13272850/147825947-89ca4caf-72c0-45e7-853a-fd91e469f0d7.png)

Second image is OpenXR runtime

![image](https://user-images.githubusercontent.com/13272850/147825961-d1c7e69b-7127-4acf-a3ce-692bc0d9e2db.png)

Third image is the scene in the editor for reference

**Comment by BastiaanOlij** [comment]
The root problem here that we've been trying to solve is that OpenXR requires us to render in linear color space while using an RGBA8 buffer, this looses too much color definition as it is converted (back to) sRGB color space for display inside of the headset, this is especially noticeable with darker colors.

For the Oculus mobile plugin everything is retained in sRGB mode and there is no color conversion that looses color definition.

Now there are sRGB color format buffers that supposedly fix this, and indeed with those we render properly when using SteamVR, but they do not seem to work on the Oculus hardware. I think this is because we are using GLES2 (as opposed to OpenGL 3 on desktop) not supporting these color formats properly.

I'm currently investigating if we can use RGB10A2 buffers so we can retain the color definition but so far it does not seem to work.

**Comment by BastiaanOlij** [comment]
On a side node, Meta did add an extension in where you supposedly can specify the color format the color buffer is in, and supposedly we should be able to tell the runtime that we are offering it an sRGB buffer. So far though this does not seem to work. Hopefully we can get some feedback from Meta engineers on this. @m4gr3d ?

**Comment by m4gr3d** [comment]
Nothing comes to mind yet, but I'll reach out and see if this is a known issue.

**Comment by BastiaanOlij** [comment]
@m4gr3d it's really interesting because to me it makes no sense to use an 8bit per color channel format like RGBA8, to store colors in linear color space as it just doesn't have the precision. Its a bit of a weird choice on the part of OpenXR so I'm pretty sure we're missing a piece of the puzzle if everyone else uses this successfully.

**Comment by BastiaanOlij** [comment]
Please test but I think #148 will fix this. Note that there are changes to the first person controller script that relate to the fix.

**Comment by BastiaanOlij** [comment]
Banding and coloring issue should now be fixed through 148. There will always be some degradation in quality on mobile and GLES2 due to vertex shading being used. If there are still issues with the 1.2.0 release of the plugin, please open a new issue with screenshots of what is not working properly yet.
