### ISSUE TITLE
Report hand tracking aiming gesture state

### ISSUE THREAD

**Issue by m4gr3d** [GodotVR/godot_openxr#194]
[XrHandTrackingAimStateFB](https://www.khronos.org/registry/OpenXR/specs/1.0/man/html/XrHandTrackingAimStateFB.html) can be used to report the aiming gesture state (e.g: pinch level for each finger).

While adding support for this is straightforward, we need to figure out (and document) the proper mechanism to dispatch pinch events to the Godot game logic.

**Comment by m4gr3d** [comment]
@BastiaanOlij Any suggestions for how to dispatch pinch events?

One option would be to leverage [`InputEventAction`](https://docs.godotengine.org/en/stable/classes/class_inputeventaction.html#class-inputeventaction) with predetermined action strings for each finger pinch events.

**Comment by BastiaanOlij** [comment]
I've already gone down the rabbit hole of trying to use Godots action system but it's really centered around Godot determining which user defined actions to trigger based on received inputs.
This is why for Godot 4 I eventually abandoned that idea and actually implemented the OpenXR action system as is and naming inputs.

My understanding of OpenXR is that the approach should be that an extension is created that defines a new interaction profile with the required input paths. So there would be a `/input/pinch_index/value` and `/input/pinch_middle/value` or something like that for the pinch values, and a `/input/aim/pose` as per usual. You can then map that to your own action. That would also mean that switching between holding a touch controller and full hand tracking would result in the interaction profile changing between `/interaction_profiles/oculus/touch_controller` and `/interaction_profiles/oculus/hand` (or whatever it would be called) which also means we know that there won't be any normal button inputs. Anyway I am ranting as usual on how I think things should be, not on how they are :P (though feel free to advocate this if you agree this solution matches the spirit of OpenXR much better then Metas current approach to this)

In this case I'm not sure if these inputs warrant events though, as they are values it's not a switch between on and off and would result in a constant stream of events.

My gut feeling says that we should expose these as separate controllers, it's a shame I'm not finished yet with the HTC tracker implementation (was waiting on a fix by Valve which is now in beta) as I'm making changes to the input map that would help out greatly here as it will be possible to register more devices that can be tracked. 

We're now using slot 1 and 2 for the left controller and right controller, we could use slot 3 and 4 for the left hand and right hand. If the FB extension is active and if the hands are tracking we use the the aim pose as its position, and we use the pinch values to set the 4 axis.

Seeing we're still piggy backing on the joystick API you could use Godots input map to trigger events if you really want to but here you run into the fundamental limitation that there is no guaranteed order to the joystick entries, whichever controller is switched on first becomes the first entry.

**Comment by m4gr3d** [comment]
Leveraging the controller api was a thought, but I'm worried this will introduce confusion for the users. If you look at the current hand tracking documentation (that you wrote :p), there's no mentions of controllers; hand tracking is a separate system with its own logic.

I think the controller approach may work if we condense the current set of classes to support hand tracking (`OpenXRHand`, `OpenXRPose`, `OpenXRSkeleton`) into a single `HandController` like extension of `ARVRController`. 
From the Godot end user point of view, this may be a win; right now there's inherently complexity in setting up hand tracking, what if we just offered the option to switch between a regular `ARVRController` and `HandController` instance to add basic hand tracking support.

**Comment by BastiaanOlij** [comment]
I don't think they can be combined into a single implementation seeing the Skeleton class applies specifically to the skeleton node containing the bones. Though seeing the way things are in Godot 4 now, that solution may not be possible anymore anyhow so there are some ideas I have about having a hand controller node where you set a nodepath to the skeleton it needs to update.

I very much like the idea of the hand controller node, it communicates much better that the controller and the hand are individually tracked, for SteamVR we will always have an active controller node tracking the controller, and an active hand node tracking the hand and offering the skeleton functionality.
On Oculus runtimes either the controller will be active, or the hand tracking will be active.

Something we can think about is whether we want to detect the situation where we have an active controller but no active hand, and create a fallback and animate bones ourselves using controller inputs (similar to what xr-tools does right now).
Similarly, if the FB extension isn't available we can determine the pinch strengths ourselves (well they would actually just be exposing trigger and grip values as approximations I guess).

This would allow us to create as much portability between platforms (though I suggest leaving some of this compatibility work for Godot 4)

Lastly, for the skeleton we now have mode where we update the positions of child nodes, a mode where we update the pose of a skeleton, we need a third one where we introduce a new component for the animation tree. This will allow you to use the animation tree to override the inputs and morph the hands into a predetermined position. Say when a player grabs an object, you want to make sure fingers are placed in predefined positions instead of their physical orientation.

**Comment by m4gr3d** [comment]
Implemented by https://github.com/GodotVR/godot_openxr/pull/197
