### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by skyace65** [GodotVR/godot_openxr#45]
I downloaded the plugin from the asset repository, imported it and enabled it in my project. VR doesn't start at all now when using OpenXR as the VR interface, this includes using the `first_person_controller_vr.tscn` scene from the plugin. This happens with "default" "SteamVR" and "Microsoft MR" from the dropdown in the top right. I have OpenXR installed for the Microsoft Mixed Reality app. I'm using Godot 3.3.2 and my project is using GLES3.

I'm not sure if this is relevant but when I tried using this code I got the error `OpenXR Runtime does not support OpenGL extension!`

```
extends ARVROrigin

func _ready():
	var arvr_interface = ARVRServer.find_interface("OpenXR")
	if arvr_interface and arvr_interface.initialize():
		get_viewport().arvr = true
```

My computer information
OS: Windows 10 (21H1)
HMD: Samsung Odyssey+
CPU: Ryzen 7 3700X
GPU: GTX 1070
RAM: 16GB

EDIT: The readme for this repository says godot needs to be compiled with the release debug target, but the readme for the asset repository doesn't mention this. Does godot still need to be compiled as release debug?

**Comment by BastiaanOlij** [comment]
@skyace65 because you have a WMR device it will try and default to the Windows OpenXR runtime which unfortunately only support DirectX based games.

It should be able to use SteamVR to work around this, the option in the dropdown list only works if SteamVR is installed in the default location. When you start SteamVR directly from Steam you should be able to set it as the default OpenXR runtime and it should chose it over the Windows one.

**Comment by skyace65** [comment]
Thank you for the help!

Changing the default runtime to SteamVR from within SteamVR fixed this. I checked and SteamVR is installed in the default location, and after switching back to WMR as the default for OpenXR the dropdown option for SteamVR started working. Maybe SteamVR has some kind of bug? Regardless the plugin works so I'll close this issue.
